import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import './global.css';
import { HeaderComponent } from '@/components/Header/Header';

const geistSans = Roboto({
  variable: '--font-roboto',
  subsets: ['latin'],
  display: 'swap',
  weight: ['400', '500', '700'],
});

export const metadata: Metadata = {
  title: 'Nova',
  description: 'Generated by Edgar Ivan Espinoza',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} antialiased`}>
        <main className="min-h-screen w-full bg-background">
          <HeaderComponent />
          {children}
        </main>
      </body>
    </html>
  );
}
